### ISSUE TITLE
request.get_json() always returning None even though I followed exact instructions

### ISSUE THREAD

**Issue by zmpeterson86** [dvf/blockchain#105]
All POST requests do not work anymore. Everything worked fine a month ago, and now it doesn't. Code has not changed, instructions have been followed exactly to the letter.

**Comment by Mat001** [comment]
@zmpeterson86 I tried POST-ing new transaction. Works for me:

```
curl -X POST -H "Content-Type:application/json" -d '{"amount": 1, "recipient": "9e3546b87ab9433ea934d9b70d7467af", "sender": "0"}' "http://localhost:5000/transactions/new"
{
  "message": "Transaction will be added to Block 2"
}
```

**Comment by Mat001** [comment]
@zmpeterson86 Can you provide details? Error messages?

**Comment by zmpeterson86** [comment]
Are you using get_json(force = True)?

**Comment by zmpeterson86** [comment]
I was only able to get it to work using force = True. I copied your code and tried it, I always get a 500 server error

**Comment by Mat001** [comment]
Hm, that's strange. 
Maybe it's flask and requests version. I'm using the latest versions, not those specified in the tutorial.

**Comment by zmpeterson86** [comment]
Now it is not working with either method.

**Comment by zmpeterson86** [comment]
I haven't changed these parts of the code and I have not updated flask or python.

**Comment by zmpeterson86** [comment]
This has worked reliably since I rolled back to a previous version of postman and used get_json(force=True)

**Comment by Krafty-Coder** [comment]
Did you update your request module? I once had the same issue on an API I was working on and I had to go through my commits to see what the problem was. (Problems of using virtual env wrapper for all your projects).
Solved it by downgrading it to some older version, can't really recall but I think it was 2.10, the request module contributors claimed that it was due to security issues that they made the changes. Still, I have no clue of using the new module though.

**Comment by darmut** [comment]
I downgraded requests to 2.10 and works fine now.

Darmut

**Comment by PicoPlanetDev** [comment]
I had a similar problem on Python 3.8 which was fixed by upgrading Flash and Requests to the newest version.

**Comment by rutefig** [comment]
If you change the format of your POST data in Postman, instead of Text (is pre selected) you select JSON it works fine
![postman](https://user-images.githubusercontent.com/23409167/100213587-b3ee9a00-2f06-11eb-9c8e-25ba9674f278.png)

**Comment by Danielratmiroff** [comment]
> If you change the format of your POST data in Postman, instead of Text (is pre selected) you select JSON it works fine ![postman](https://user-images.githubusercontent.com/23409167/100213587-b3ee9a00-2f06-11eb-9c8e-25ba9674f278.png)

Thank you! that was it

**Comment by codemaker2015** [comment]
Try to set force attribute as True in get_json() method to resolve this issue.

`request.get_json(force = True)`

**Comment by Barten74** [comment]
In my case the reason was that my json file had format: {'name': 'John'}. But then I found error that says "Expecting property name enclosed in double quotes". So I changed json file to {"name": "John"} and it worked.
