### ISSUE TITLE
Transaction Not Working

### ISSUE THREAD

**Issue by developingcountries** [dvf/blockchain#108]
Hello, I'm having a problem where I can only mine new blocks but I can't create a transaction.  
I followed the instructions at https://hackernoon.com/learn-blockchains-by-building-one-117428612f46. I'm using Postman to process the HTTP operations and I'm using the code at https://github.com/dvf/blockchain/blob/master/blockchain.py

For I example I start by mining 2 new blocks, and here is the chain:

```
{
    "chain": [
        {
            "index": 1,
            "previous_hash": "1",
            "proof": 100,
            "timestamp": 1524517101.7181187,
            "transactions": []
        },
        {
            "index": 2,
            "previous_hash": "563ff3b8271b9a04802d14a59ce216205a1d60fac316486895966f8645ba4545",
            "proof": 79884,
            "timestamp": 1524517144.4791226,
            "transactions": [
                {
                    "amount": 1,
                    "recipient": "be8864f72e6b4dba86c15cd331fdb927",
                    "sender": "0"
                }
            ]
        },
        {
            "index": 3,
            "previous_hash": "b606814f812da8bdb69af0ac5aac69ad0daa1a530038c564d9e51587cedd03e0",
            "proof": 85296,
            "timestamp": 1524517188.1898813,
            "transactions": [
                {
                    "amount": 1,
                    "recipient": "be8864f72e6b4dba86c15cd331fdb927",
                    "sender": "0"
                }
            ]
        }
    ],
    "length": 3
}
```

Then I try a transaction at the Post endpoint: http://localhost:5000/transactions/new with this json in the body:
```
{
 "sender": "d4ee26eee15148ee92c6cd394edd974e",
 "recipient": "be8864f72e6b4dba86c15cd331fdb927",
 "amount": 1
}
```
It gives a 201 response:
```
{
    "message": "Transaction will be added to Block 4"
}
```
But when I view the chain at http://localhost:5000/chain, it doesn't show block 4:
```
{
    "chain": [
        {
            "index": 1,
            "previous_hash": "1",
            "proof": 100,
            "timestamp": 1524517101.7181187,
            "transactions": []
        },
        {
            "index": 2,
            "previous_hash": "563ff3b8271b9a04802d14a59ce216205a1d60fac316486895966f8645ba4545",
            "proof": 79884,
            "timestamp": 1524517144.4791226,
            "transactions": [
                {
                    "amount": 1,
                    "recipient": "be8864f72e6b4dba86c15cd331fdb927",
                    "sender": "0"
                }
            ]
        },
        {
            "index": 3,
            "previous_hash": "b606814f812da8bdb69af0ac5aac69ad0daa1a530038c564d9e51587cedd03e0",
            "proof": 85296,
            "timestamp": 1524517188.1898813,
            "transactions": [
                {
                    "amount": 1,
                    "recipient": "be8864f72e6b4dba86c15cd331fdb927",
                    "sender": "0"
                }
            ]
        }
    ],
    "length": 3
}
```

Is there something that I'm missing?  Thanks.

**Comment by Mat001** [comment]
@developingcountries You need to call /mine endpoint again for the new transaction to be added to block 4.
You can post as many transactions as you want. they will all go to "transactions" list. They will wait there until you mine again. 
Process of mining is creating a block from transactions and validating it.

**Comment by Mat001** [comment]
What's perhaps the confusing bit is that it's possible to hit /mine endpoint when no transactions are yet created. I don't know why is that. Mining makes sense when there are transactions.

**Comment by zmpeterson86** [comment]
The comment in the code says that the /mine endpoint is designed to create the genesis block, that is definitely one source of confusion

**Comment by developingcountries** [comment]
Thank you Mat001 and zmpeterson86. OK, so I did a mine first, then a transaction, and then another mine, and now it works. Thanks so much for your help.
