### ISSUE TITLE
All post requests return 400 error

### ISSUE THREAD

**Issue by zmpeterson86** [dvf/blockchain#113]
I have not modified the code on any post requests, and I always get a 400 error. I think the problem is I can't convert the values variable into a JSON. Can anyone help? I've spent days trying to get this to work. It used to work fine and now it doesn't, even though I haven't changed anything in the code

I'm running python 3.6.2

**Comment by Mat001** [comment]
@zmpeterson86 Can you post some code or errors?
Might help in debugging.
Also are you using pipenv to set up virtualenv?
If you did everything as instructed, then you may have done either atype or something config-wise has gone wrong.
Post some code...

**Comment by zmpeterson86** [comment]
This was actually a postman problem, not a blockchain problem. I had to roll back to a previous version of postman to fix this.
