### ISSUE TITLE
pipenv install issues: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ishandutta2007** [dvf/blockchain#125]
ishandutta2007@MacBook-Pro:~/Documents/Projects/blockchain$ `pipenv install`

>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/bin/pipenv", line 11, in <module>
>     sys.exit(cli())
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
>     selective_upgrade=selective_upgrade,
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/core.py", line 1759, in do_install
>     pypi_mirror=pypi_mirror,
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/core.py", line 614, in ensure_project
>     path_to_python = which('python') or which('py')
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pipenv/core.py", line 115, in which
>     p = os.path.join(location, 'bin', command)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/posixpath.py", line 81, in join
>     a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by CoreyCole** [comment]
> TypeError: expected str, bytes or os.PathLike object, not NoneType
I've seen this error before. I think it means pipenv cannot find python in your path. You can fix that, or you can run pipenv with the `--python` argument and specify where the version of python you want to use it located.

**Comment by dvf** [comment]
Strange, check out this guide I wrote to get a nice Python environment set up: https://gist.github.com/dvf/e35c4ac2e1e797f93427200ab5cad74c
