### ISSUE TITLE
docker: Server running but not receiving any request

### ISSUE THREAD

**Issue by ishandutta2007** [dvf/blockchain#126]
**1st Terminal Window**
ishandutta2007@MacBook-Pro:~/Documents/Projects/blockchain$ `docker run --rm -p 80:5000 blockchain`

>  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

**2nd Terminal Window**
ishandutta2007@MacBook-Pro:~/Documents/Projects$ `curl http://127.0.01:5000/chain`
>  curl: (7) Failed to connect to 127.0.01 port 5000: Connection refused

**Comment by passionofvc** [comment]
@ishandutta2007 

wrong : curl http://127.0.01:5000/chain
correct:curl http://127.0.0.1:5000/chain

http://127.0.0.1 means localhost, 127.0.01 is not a IP.
