### ISSUE TITLE
ImportError: cannot import name 'Flask'

### ISSUE THREAD

**Issue by alex-manutd** [dvf/blockchain#129]
Hi Everyone,

Python N00b.  I have searched issues but couldn't find a solution to the same problem as mine. 

I am at STEP 3: and am getting the following error when I run python3.6 blockchain.py:

(It could be relevant that I haven't installed Postman yet.)

Traceback (most recent call last):
  File "blockchain.py", line 7, in <module>
    from flask import Flask, jsonify, request
ImportError: cannot import name 'Flask'
alex@alex-XPS-13:~/Projects/python/blockchain$

Thanks for your help kindly.

**Comment by smouli** [comment]
try: pip install flask

**Comment by dvf** [comment]
Just do `pip install -U pipenv && pipenv install && pipenv shell`

**Comment by alex-manutd** [comment]
Thanks everyone.  My problem persists after trying each proposed solution.
I do have pip installed.
When I cut and paste the code from Github into a file called blockchain2.py and run that, I get the same error :-|

**Comment by Victorvick399** [comment]
It did not work and error message is
Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from app import create_app,db
  File "/home/victor/Documents/Pitches/app/__init__.py", line 1, in <module>
    from flask import Flask
ImportError: cannot import name 'Flask'

**Comment by Harishyadav766** [comment]
for me also it coming same error even though i installed all dependencies. can any one help me out with this

Traceback (most recent call last):
  File "flask.py", line 1, in <module>
    from flask import Flask
  File "/home/harishwojtyla/Desktop/flask-jwt/tests/flask.py", line 1, in <module>
    from flask import Flask
ImportError: cannot import name 'Flask'

**Comment by CaydendW** [comment]
Have you named your project flask.py or Flask.py? If you have, change it. It is trying to import itself and is failing causing an import error.

**Comment by Abderrahmane-Boujendar** [comment]
@CaydendW  you are a life saver tanks bro

**Comment by CaydendW** [comment]
Glad I could help @Abderrahmane-Boujendar

**Comment by TalMoshel1** [comment]
hey guys, did all the solutions you have written,
still got the problem: cannot import name 'Flask' from 'flask'
any more help?

**Comment by CaydendW** [comment]
What's the file name for your project?

**Comment by TalMoshel1** [comment]
its "API endpoints.py"
thank you

**Comment by afjal6000** [comment]
i changed the name but still not working
ImportError: cannot import name 'Flask' from partially initialized module 'webf' (most likely due to a circular import)

**Comment by dhanushdevan** [comment]
This error happen to me
