### ISSUE TITLE
Cant run the server with pipenv

### ISSUE THREAD

**Issue by trbryant97** [dvf/blockchain#131]
Using pipenv run python blockchain.py and it runs the server on http://0.0.0.0:5000/. Everytime I go to the page I get a "This site cannot be reached". Am I doing something wrong?

![image](https://user-images.githubusercontent.com/42814568/46929172-36a88980-d00c-11e8-8fc2-6a330ed782b8.png)

**Comment by trbryant97** [comment]
![image](https://user-images.githubusercontent.com/42814568/46929261-a0c12e80-d00c-11e8-9c56-4dd3e043b3c9.png)

**Comment by trbryant97** [comment]
Ran localhost:5000 fixed

**Comment by MyMetalTiger** [comment]
I to I y
