### ISSUE TITLE
Generalize your lib

### ISSUE THREAD

**Issue by ratoshniuk** [dvf/blockchain#132]
Hi, @dvf ! 

What do you think to refactor it a bit by adding support for other languages like Golang, Scala, Rust, Haskell? 

I am planning to add by myself for Golang and Scala? 

I think it could increase number of users interested and build useful stuff for every interested in

**Comment by dvf** [comment]
Do these languages allow you to import Python libraries or do you mean compile to C?

**Comment by ratoshniuk** [comment]
I meant implement by yourself for each programming language.

Or, we can use GraalVM for python libraries
