### ISSUE TITLE
404 on /nodes/register and nodes/resolve

### ISSUE THREAD

**Issue by alex-manutd** [dvf/blockchain#136]
Hello,

I have finished coding and spun up a secondary node from my desktop computer by running a POP_OS VM in virtualbox under Bridged mode but I am stuck at 404 error.

I cannot register a new node or resolve but the routes from Steps #1 and #2, /transactions/new, /mine and /chain work fine from both nodes in both directions and even from my Samsung tablet.  

I am using Postman on both nodes (Linux Mint natively and POP_OS on Virtualbox on Win10).

I have installed several HTTP request apps on my Samsung tablet and while I can interact with the working methods on both nodes I cannot access the two problematic methods /nodes/register and /nodes/resolve.

It behaves as if the routes are not even in my code.  When I intentionally misspell the route then try to access it, the same 404 error occurs.

My next step will be trying it using cURL.  

Can anyone begin to explain why this could occur with functional routes?

**Comment by alex-manutd** [comment]
Solved.
Did not see the code differences between Hackernoon and Github.

**Comment by trbryant97** [comment]
> Solved.
> Did not see the code differences between Hackernoon and Github.

Did hackernoon have updated code?

**Comment by alex-manutd** [comment]
I do not believe so.  For instance my problem was that I was missing 5 out of the last 6 lines of code, which are not in Hackernoon.

**Comment by MoH-MuRRa** [comment]
> I do not believe so. For instance my problem was that I was missing 5 out of the last 6 lines of code, which are not in Hackernoon.

I have an error with nodes/resolve. When I try to activate it before registering a node it works fine, but after I register a new node and try to do it again I get an error number 500. U know why?
