### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by skidzo** [dvf/blockchain#14]
Your docstrings need improvement::

    :param last_proof: <int> Previous Proof
    :param proof: <int> Current Proof
    :return: <bool> True if correct, False if not.

this is a bit weired, if you consider sphinx, which is the default, you would write it like this::

    :param last_proof: previous proof
    :type last_proof: int
    :param proof: current proof
    :type proof: int
    :rtype: bool

**Comment by dvf** [comment]
Thanks, do you mind submitting a PR?

**Comment by skidzo** [comment]
ok

**Comment by skidzo** [comment]
will you merge the PR #17 ?
