### ISSUE TITLE
Trouble with pipenv on MacOS

### ISSUE THREAD

**Issue by rupe120** [dvf/blockchain#15]
I was following the recommended steps to setup the project with pipenv, but pipenv is somehow not being installed into the path. 

I tried `pip install pipenv` with and without `sudo` on MacOS, with no luck. The install appears successful, but I only get "command not found" when I try to run pipenv

Any suggestions?

(As a side note, how do I attach a label to an issue? I saw the suggestion to add a "help wanted" label but I don't see how to add that.)

**Comment by Endogen** [comment]
Maybe you have more then one Python version installed and installed pipenv with another version then you run the code?

**Comment by rupe120** [comment]
That was it. I had to run pip3 and not pip. With the requirement of Python 3.6 I'm surprised that more people haven't commented on the steps to setup the environment referencing pip instead of pip3

**Comment by Endogen** [comment]
The thing is, for you it's `pip3`, for me it's `pip3.6` for other folks it can be `pip`. That is not something that is the same for all users. I think it would be a bit clearer if the README used `pip3` bis since it's not always that...

**Comment by Endogen** [comment]
Please close the issue if you feel that your question is answered

**Comment by rupe120** [comment]
Got it, thanks
