### ISSUE TITLE
I need a bunch of those bcoin cashed into my TD Bank account.....they were good right? I'm broke....homeless... my daughter is I. Foster care.....my wife is on the street......I knew they were good.....why did you stop them?

### ISSUE THREAD

**Issue by joekewl70** [dvf/blockchain#159]
That was a year and a half of my life... 80 hour weeks....trying to get my life and my family together.....and you stopped it every time? Why?

**Comment by joekewl70** [comment]
I need like 20 M......keep the rest.....
I just want my family back together set for the rest of our lives....do you realize I almost committed suicide while you withheld this all? My wife Lmosy commited suicide.....our daughter was taken by the ministry.....and you just kept every thing I made.........I dedicated my life to set my family up.........NOW can you set me up???? I want to go get my daughter.

**Comment by joekewl70** [comment]
Its been a terribly rough 2 years

**Comment by joekewl70** [comment]
TD Canada Trust 98860 004 6160779...... And please let her know....get a lawyer to get my daughter..... Please

**Comment by ourway** [comment]
Amazing that a spammer broke my concentration time to beg for money. Get out of here.

**Comment by joekewl70** [comment]
These are my files you fuck

**Comment by joekewl70** [comment]
Looks like I'm smarter then you if I could do all this you freak

**Comment by joekewl70** [comment]
I'll report all this sjotif it's not released

**Comment by joekewl70** [comment]
I'm not asking for much...... just Enoch to be comfortable...
I created approx 500 B so what's fucking 20M?

**Comment by joekewl70** [comment]
And yes I love my family please

**Comment by ourway** [comment]
@dvf Please ban this user.

**Comment by joekewl70** [comment]
@dvf please hear my plea
