### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by mrpbennett** [dvf/blockchain#201]
Within the end point `'/transactions/new'`

it seems that `values = request.get_json()` is None

I get the following error:

``` 
if not all(k in values for k in required):
TypeError: argument of type 'NoneType' is not iterable
```

Flask docs state `request.get_json()` will return None by default. I have also tried the source code and get the same error.

This is the debug output from pycharm

```python
@app.route('/transactions/new', methods=['POST'])
def new_transaction():
    values = request.get_json()    values: None

    # Check that the required fields are in the POST'ed data
    required = ['sender', 'recipient', 'amount']    required: ['sender', 'recipient', 'amount']

    if not all(k in values for k in required): # break point here
        return 'Missing values', 400
```

**Comment by Bchass** [comment]
Update the line to `values = request.get_json(force=True)`

**Comment by mrpbennett** [comment]
yup just changed that and it works.

`values = request.get_json(force=True)` was going to post my answer.
