### ISSUE TITLE
Add Continuous integrations like TravisCI, HoundCI and Codecov. 

### ISSUE THREAD

**Issue by bhaveshAn** [dvf/blockchain#22]
There is a need to add implementation of following CIs in this project. 
* Travis 
* Hound 
* Codecov 

**Yes, I would like to work on this issue**

**Comment by dvf** [comment]
Yeah, I agree. Let's do it.... but that means we'll need some tests first.

**Comment by dvf** [comment]
I've added some tests and added Travis Integration 👍
