### ISSUE TITLE
an error in typing hint

### ISSUE THREAD

**Issue by pony-maggie** [dvf/blockchain#25]
`
@property
    def last_block(self) -> Dict[str : Any]:
        return self.chain[-1]
`

should be:

`
@property
    def last_block(self) -> Dict[str , Any]:
        return self.chain[-1]
`

**Comment by Endogen** [comment]
There is already a PR for that: #19 It's just that @dvf didn't merge it yet

**Comment by dvf** [comment]
I've merged #19
