### ISSUE TITLE
Error TypeError: new_block()

### ISSUE THREAD

**Issue by capacitate** [dvf/blockchain#27]
Thank you for the kind [article](https://hackernoon.com/learn-blockchains-by-building-one-117428612f46)

I enjoyed it and tried to reproduce it and play it

I got this error

I used python==3.6.3, Flask==0.12.2, and requests==2.18.4 

>   File ".\blockchain.py", line 204, in mine
    block = blockchain.new_block(proof)
TypeError: new_block() missing 1 required positional argument: 'previous_hash'

**Comment by Endogen** [comment]
There is already a PR for that: #30 It's just that @dvf didn't merge it yet

**Comment by capacitate** [comment]
@Endogen, Yes you're right. The line number 135 issue was already solved by PR #19. 

but, I got another error when playing with postman to send Get request to "mine" 

so, I add empty list to the "new_block" function. 

Thank you for pointing out 👍

**Comment by dvf** [comment]
This is fixed in https://github.com/dvf/blockchain/pull/35
