### ISSUE TITLE
Data analysis from the chain

### ISSUE THREAD

**Issue by hskang9** [dvf/blockchain#39]
I think it would be great to display the current information from the blockchain such as the number of users, transactions, and coins within the process.

**Comment by Endogen** [comment]
Great idea! I would also like to see that. Would be nice to visualize that data somehow. Any idea how that could be done?

**Comment by stevenpack** [comment]
I personally don't think that makes sense for the core blockchain. It already returns the entire chain. You could have an analysis node or a visualization node download the data and then provide those services. [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle).

**Comment by Endogen** [comment]
Ok, true. I also think that this should not be part of the core blockchain.

**Comment by hskang9** [comment]
We may see it on part 2 though.

**Comment by dvf** [comment]
@hskang9 I'm busy working on Part 2 and if there's time we can include a web-component to it.
