### ISSUE TITLE
Length field validity not checked during consensus

### ISSUE THREAD

**Issue by TimelessP** [dvf/blockchain#50]
The /chain request handler could lie about its own chain's length being longer than the actual number of items in the chain because the consensus code doesn't check that the number of items matches the length field value. Theoretically, this could be used to impose one's own chain on all nodes. Effects might include: falsifying transactions and deletion of transactions for profit.

Full disclosure on the bug report because I understand that the spirit of this code was a learning exercise.
Found this code via: https://hackaday.com/2017/11/23/learn-about-blockchains-by-building-one/ "You are not going to launch a cryptocurrency using this code..." (correct!), and https://hackernoon.com/learn-blockchains-by-building-one-117428612f46

**Comment by dvf** [comment]
@TimelessP the resolve function doesn't care about advertised length: it still brute-forces the validity of the entire chain and counts it as it goes. I may be wrong, but do you mind stepping through the `/resolve` endpoint and checking that there is in fact a bug?

Happy to re-open.

**Comment by TimelessP** [comment]
@dvf apologies for not being clearer about which code was at fault; the fix should be fairly simple:
https://github.com/dvf/blockchain/blob/4010cf3273e19146a9cd7b37cf355cb751ffef88/blockchain.py#L82
Currently it reads:
`if length > max_length and self.valid_chain(chain):`
I suggest a change as follows:
`if length > max_length and self.valid_chain(chain) and length == len(chain):`
(and then of course the same fix needs to be applied to the C# code)

**Comment by TimelessP** [comment]
In hindsight, I'd move the comparison to before the valid_chain() call so as to save time on invalid chains. To be even clearer to those porting this code to other languages one might even consider explicitly putting brackets around the comparisons so that the order of evaluation is read as being important.

**Comment by dvf** [comment]
Thanks @TimelessP do you mind submitting a PR?

**Comment by TimelessP** [comment]
pass.
