### ISSUE TITLE
Cant access localhost

### ISSUE THREAD

**Issue by imvaibhav28** [dvf/blockchain#53]
:blockchain-master Vaibhav$ docker run --rm -p 80:5000 blockchain
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
172.17.0.1 - - [08/Dec/2017 18:46:05] "GET / HTTP/1.1" 404 -
172.17.0.1 - - [08/Dec/2017 18:46:11] "GET / HTTP/1.1" 404 -

Tried everything from 127.0.0.1:80 to localhost:5000

But everytime i get same 404 error.
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by imvaibhav28** [comment]
OS: MacOS Sierra 10.12.1

**Comment by Zero-1729** [comment]
That is expected. You get an Error 404 message each time you make a GET request to http://127.0.0.1:5000 or http://localhost:5000 because nothing is being served from the default route '/'. The only available links according to the source code are '/chain',  '/mine', etc. 

Re-run the script again and try either http://127.0.01:5000/chain or http://localhost:5000/chain. You should now be able to see the blockchain.

**Comment by imvaibhav28** [comment]
Hey thanks for replying.
But the issue still persists 

docker run --rm -p 80:5000 blockchain
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

and still not able to load 

This site can’t be reached

localhost refused to connect.
Search Google for localhost 5000 chain
ERR_CONNECTION_REFUSED

**Comment by Zero-1729** [comment]
Hmm :thinking: Running the script locally on my machine I get the following 

![screenshot](https://user-images.githubusercontent.com/23586626/33809118-b8574894-ddf1-11e7-981b-72258f72fcde.png)

From making these requests
![screenshot1](https://user-images.githubusercontent.com/23586626/33809117-b80798f8-ddf1-11e7-96e2-deab1c18ff26.png)

Though I am not too seasoned with Docker I managed to do some digging. 
Your issue could be with docker's default IP set up on your machine.

check this [here](https://serverfault.com/questions/728292/getting-err-connection-refused-when-trying-to-browse-port-mapped-to-docker-con) to see if is of any help. 

Just noticed my date/time was messed up by some program :laughing:

**Comment by dvf** [comment]
AFAIK you need root to listen on port 80. Can you try `docker run --rm -p 8000:5000 blockchain` instead?
