### ISSUE TITLE
"resolve_conflicts" is not easy to run with condition

### ISSUE THREAD

**Issue by awt135** [dvf/blockchain#64]
"I then mined some new Blocks on node 2, to ensure the chain was longer. Afterward, I called GET /nodes/resolve on node 1, where the chain was replaced by the Consensus Algorithm:"

i follow the steps, but redo the several times , the code cant run to  “  'message': 'Our chain was replaced',”， it seem like some anything wrong “replaced = blockchain.resolve_conflicts()” ？

dont understand when i run three instances for docker， and  miner insert some data， then make three instances list is not same(node_B list data more node_A) ，then add register node node_A to node_B , then POST node_B  "nodes/resolve". but wait a little long time,(it seem like node_B replace the list ) but  the node_B is not changed,   it is so wried ....

thx for help~

**Comment by Sinotov** [comment]
Maybe this will solve the problem https://github.com/dvf/blockchain/issues/66
