### ISSUE TITLE
Postman - Something went wrong. And we are reporting a custom error message.

### ISSUE THREAD

**Issue by brazilian-noob** [dvf/blockchain#69]
In the program Postman when I do GET    http://localhost:5001/mine, I receive the Error Message: "Something went wrong. And we are reporting a custom error message."

In the CMD on Win7 the blockchain.py is running correctly.

I'm stuck on this step.

**Comment by zhouzhou84** [comment]
File "blockchain.py", line 50
print(f'{last_block}')
^
SyntaxError: invalid syntax

that single quote mark has some problems ,could you please help me...

**Comment by dvf** [comment]
@zhouzhou84 you need to use Python 3.6 +

**Comment by dvf** [comment]
@brazilian-noob I'm not sure what's going on. Sounds like a Postman issue.
