### ISSUE TITLE
I have a questions about Blockchain class

### ISSUE THREAD

**Issue by skyepodium** [dvf/blockchain#70]
I read your post https://hackernoon.com/learn-blockchains-by-building-one-117428612f46
and implement with django, django rest framework https://github.com/skyepodium/blockchain_django
your post is very helpful and make easy to learn about blockchain

but i have a question
when i shut down or restart django server, Blockchain class disappeared. because of a lifecycle

summary
How can I safely manage the block chain regardless of the server restart?

**Comment by JimiPedros** [comment]
@skyepodium have you managed to get 2 nodes to communicate on one chain with unique address assigned to each? If so can you please let me know? Thanks!

**Comment by severikupari1** [comment]
Did you use different ports to each node? I had issue with that in c# project.

**Comment by JimiPedros** [comment]
Yes, I am running `pipenv run python blockchain.py -p 5000` and `pipenv run python blockchain.py -p 5001` in two seperate terminals.

Could you please explain how you can setup two nodes to communicate?

I have tried everything; 
- registering a node via 'nodes/register' route
- trying to connect to a node running the server on it's localhost port 5000 via it's ipv4 address i.e, `192.168.1.6:5000`

Not sure what else to try..

```
$ pip3 freeze 

certifi==2018.1.18
chardet==3.0.4
click==6.7
Flask==0.12.2
idna==2.6
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
requests==2.18.4
urllib3==1.22
Werkzeug==0.14.1
```

```
$ which python3.6.3

certifi==2018.1.18
chardet==3.0.4
click==6.7
Flask==0.12.2
idna==2.6
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
requests==2.18.4
urllib3==1.22
Werkzeug==0.14.1
```

```
$ which python3
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
```

**Comment by dvf** [comment]
@skyepodium you'll have to persist the chain to a database, or some sort of storage. Nice work!

**Comment by lauramayol** [comment]
@skyepodium FYI - I have solved the issue where Blockchain disappears by storing the data on a database. You can refer to my project here: https://github.com/lauramayol/my_blockchain
