### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by LEscobar-Driver** [dvf/blockchain#74]
Line 50-51 in blockchain.py

print(f'{last_block}')
print(f'{block}')

My compiler reads this as invalid syntax. I have never seen python syntax like that, care to explain what it means?

**Comment by jcyktor** [comment]
Those are [f-strings](https://www.python.org/dev/peps/pep-0498/) - added in 3.6.

**Comment by LEscobar-Driver** [comment]
yea figured it out last night. Another formatting tool lol
