### ISSUE TITLE
Strengthen the "Proof-of-work"

### ISSUE THREAD

**Issue by JeremyMet** [dvf/blockchain#81]
Hello People,
I was reading your code, what a nice little project ! 
I've been asking myself about the "Proof-of-Work" (PoW) part. I think PoW might be somehow broken. As far as I understand, "Proof-of-Work" is done before rewarding the miner, i.e. a node finds a solution, then a new block is created including the "proof". Finally, the node pushes a new transaction that rewards itself. But this last transaction is not "linked" to any other in a sense that one would be able to easily modify it and to forge a new transaction that gives one the fresh mined coin (i.e. one could use a proof that he did not generate).  It would be very easy to "correct" it so far, moving the proof_of_work right after the new_transaction instruction. 
Actually, it seems there is something more painful as none of the "current block transactions" are part of PoW. Since then, one could forge a whole new block without any effort based on the last proof. 
Maybe Am I misunderstanding the whole design ?
Thanks for your project, 
I think I'll contribute to it very soon :-)

**Comment by dvf** [comment]
You're partially correct @JeremyMet. In most blockchain implementations, the block currently being mined has a set of frozen transactions in it while the `proof` is being searched for. The block also contains the previous hash.

For the simplicity of this explanation, we'd need to implement multithreading/multiprocessing to be able to mine whilst receiving transactions.
