### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zhouzhou84** [dvf/blockchain#84]
File "blockchain.py", line 50
    print(f'{last_block}')
                               ^
SyntaxError: invalid syntax

that single quote mark has some problems ,could you please help me...

**Comment by sdpetrides** [comment]
Make sure that you are running Python 3.6+. There are installation instructions on the [README.md](https://github.com/dvf/blockchain#installation).

You can check what version you are running with the following command:
`$ python -V`
or 
`$ python3 -V`

Use this command if you follow the installation instructions:
`$ pipenv run python --version`

**Comment by dvf** [comment]
What @sdpetrides said^^
