### ISSUE TITLE
Method Not Allowed for /transactions/new

### ISSUE THREAD

**Issue by sunandiyer** [dvf/blockchain#86]
I get a 405 Method Not Allowed error when running this. Did anyone else have this issue? I am running code directly pulled from this repo

**Comment by JimiPedros** [comment]
update `values = request.get_json()` to `values = request.get_json(force=True)`

**Comment by dvf** [comment]
Can you submit a PR?

**Comment by driftalong2** [comment]
> update `values = request.get_json()` to `values = request.get_json(force=True)`

It doesn't seem to work
